src/app/__init__.py
import os

from flask import Flask
from flask_bootstrap import Bootstrap

from src.app.config import config, config_factory
from src.config_manager import ConfigManager
from src.fetcher_factory import FetcherFactory

config_manager = ConfigManager()
fetcher = FetcherFactory(config=config_manager).get_fetcher()


def create_app(config_type: str) -> Flask:
    app = Flask(__name__.split(".")[0], root_path=os.path.join(os.getcwd(), "src/app"))
    app_config = config_factory.get_config(config_type)
    app.config.from_object(app_config)

    app_config.init_app(app)
    Bootstrap(app)

    from src.app.main import main as main_blueprint

    app.register_blueprint(main_blueprint)

    from src.app.api import api as api_blueprint

    app.register_blueprint(api_blueprint, url_prefix="/api/v1")

    return app

src/app/api/__init__.py
from flask import Blueprint

api = Blueprint("api", __name__)

from src.app.api import views, errors

src/app/api/views.py
import logging
from typing import Dict, List

from flask import jsonify, request

from src.app.api import api
from src.app.exceptions import InvalidUsage
from src.flattener import Flattener
from src.parser import Parser
from src.validator import Validator


logging.basicConfig(
    format="%(asctime)s %(levelname)-8s %(message)s",
    level=logging.INFO,
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


@api.route("/get_hours_for_humans", methods=["POST"])
def get_hours_for_humans():
    try:
        content: Dict[str, List[Dict[str, str]]] = request.json
        logger.log(level=logging.INFO, msg=content)

        parser = Parser()
        parsed_input = parser.parse_json_in(json_in=content)

        validator = Validator(parsed_input=parsed_input)
        validator.validate()

        flattener = Flattener(parsed_input=parsed_input)

        result = flattener.flatten_to_string()
        logger.log(level=logging.INFO, msg=result.replace("\n", " "))
        return jsonify(output=result)
    except RuntimeError as err:
        logger.log(level=logging.INFO, msg=err)
        raise InvalidUsage(str(err), status_code=400)

src/app/app.py
import os

import click

from src.app import create_app

app = create_app(os.getenv("FLASK_CONFIG", "default"))


@app.cli.command()
@click.argument("pytest_arg", nargs=-1)
def test(pytest_arg):
    import pytest

    if not pytest_arg:
        pytest.main(["-x", "-s", "-v", "--disable-pytest-warnings", "tests/"])
    else:
        pytest.main([f"tests/{str(pytest_arg[0])}"])

src/app/main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__)

from src.app.main import views, errors

src/app/main/views.py
import io

from flask import send_file, render_template

from src.app import fetcher
from src.app.main import main


@main.route("/", methods=["GET"])
def index():
    return render_template("index.html")


@main.route("/icon", methods=["GET"])
def icon():
    return send_file(
        io.BytesIO(fetcher.fetch_image("my_face.jpg")), mimetype="image/jpeg",
    )


@main.route("/health", methods=["GET"])
def health():
    return "", 200

src/app/templates/base.html
{% extends "bootstrap/base.html" %}


{% block title %}Opening Hours{% endblock %}

{% block metas %}
    {{ super() }}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
{% endblock %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="icon" href="{{ url_for("main.icon") }}" type="image/x-icon">
    <link rel="shortcut icon" href="{{ url_for("main.icon") }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="styles.css") }}">
{% endblock %}

{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">OH</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}

        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-163853319-5"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());
        gtag('config', 'UA-163853319-5');
    </script>
{% endblock %}

src/app/templates/index.html
{% extends "base.html" %}

{% block page_content %}
    <body>
        <div class="page-header">
            <header>
                <h1>Tanner's Submission for Wolt's Coding Challenge</h1>
            </header>
        </div>

        <div class="section">
            <article>
                <p>
                    This site only includes an API for now, though a basic front-end could be added.
                    You can find out more at
                    <a href="https://github.com/m-tanner/OpeningHours" target="_blank"
                       style="color: #B200FD; text-decoration: underline; display: inline-block">the Github repo</a>
                    or head straight to the API, using something like
                    <code>
                        curl -X POST https://woltchallenge.app/api/v1/get_hours_for_humans -H "Content-Type:
                        application/json" -d
                        '{"monday": [],
                        "tuesday": [
                        {
                        "type": "open",
                        "value": 36000
                        },
                        {
                        "type": "close",
                        "value": 64800
                        }
                        ],
                        "wednesday": [],
                        "thursday": [
                        {
                        "type": "open",
                        "value": 36000
                        },
                        {
                        "type": "close",
                        "value": 64800
                        }
                        ],
                        "friday": [
                        {
                        "type": "open",
                        "value": 36000
                        }
                        ],
                        "saturday": [
                        {
                        "type": "close",
                        "value": 3600
                        },
                        {
                        "type": "open",
                        "value": 36000
                        }
                        ],
                        "sunday": [
                        {
                        "type": "close",
                        "value": 3600
                        },
                        {
                        "type": "open",
                        "value": 43200
                        },
                        {
                        "type": "close",
                        "value": 75600
                        }
                        ]
                        }'
                    </code>.
                </p>
                <p>
                    Cheers,<br/>
                    Tanner
                </p>
            </article>
        </div>

        <div class="footer">
            <footer>
                <p>
                    <a href="https://friendlyventures.io/" target="_blank">Tanner's Résumé</a>
                </p>
            </footer>
        </div>
    </body>
{% endblock %}